### ISSUE TITLE
Versions numbers

### ISSUE THREAD

**Issue by aplavin** [rory-linehan/OpenAI.jl#20]
Changing the first non-zero number in a package version means a breaking change. As far as I see, OpenAI.jl only adds new features in recent versions, doesn't break anything.
So, according to how Julia treats package versions, they should go 0.1.0, 0.1.1, 0.1.2, etc for new features. And 0.1.0, 0.2.0, etc should be reserved for breaking changes. See https://pkgdocs.julialang.org/v1/compatibility/.

**Comment by rory-linehan** [comment]
Ahh, I wasn't aware of the nuances with leading zeros. I suppose the solution would be to correctly version from here on out? I assume that mutating tags would be bad because the general registry entries would break.
