### ISSUE TITLE
Collaboration on OpenAI.jl

### ISSUE THREAD

**Issue by logankilpatrick** [rory-linehan/OpenAI.jl#3]
Hey @rory-linehan! I am working on an article about using the OpenAI API in Julia. I wanted to propose some changes and such. Can you add me a collaborator here? I would also be interested in getting this moved to the JuliaML or JuliaAI org at some point.

**Comment by rory-linehan** [comment]
Sure! I've added you. Sorry about the delay. Let me take a look at the other issue.

**Comment by logankilpatrick** [comment]
Hey! Can you invite me again? The link expired.

**Comment by logankilpatrick** [comment]
Got it !
